language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r travis_bot/requirements.txt
script:
- flake8 . | ./travis_bot/travis_bot.py
env:
  global:
  - TRAVIS_BOT_GITHUB_TOKEN=fd79e0549a039717a0a4feb53fd8020cbf6bdb0f
